sudo: required
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - RELEASE_NAME="mdot"
    - DJANGO_APP="mdot"
    - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
    - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
install:
  - docker build -t "${IMAGE_TAG}" .
before_script:
  - pip install coverage
  - pip install coveralls
script:
  - docker run -u root -it -v /tmp/coverage -e DJANGO_APP="${DJANGO_APP}" -e "ENV=localdev" "${IMAGE_TAG}" bash -c ". ./travis/test.sh"
  # - recess mdot/static/mdot/css/*.less --noIds false
  # This actually fails the test if there are recess errors :(
  # - if recess mdot/static/mdot/css/*.less --noIds false | grep Busted | grep --quiet Busted ; then `exit 1`; fi
after_success:
  - cp /tmp/.coverage.* .
  - coverage combine
  - coveralls
