sudo: false
language: python
python:
  - "2.7"
install:
  # - npm install recess
  - pip install .
  - pip install pycodestyle
  - pip install coverage
  - pip install coveralls

before_script:
  - cp sampleproj/manage.py manage.py
  - python manage.py migrate --noinput --settings=sampleproj.settings.travis
script:
  - pycodestyle mdot/ --exclude=migrations
  - coverage run --source=mdot/ --omit=mdot/migrations/* manage.py test mdot --settings=sampleproj.settings.travis
  # - recess mdot/static/mdot/css/*.less --noIds false
  # This actually fails the test if there are recess errors :(
  # - if recess mdot/static/mdot/css/*.less --noIds false | grep Busted | grep --quiet Busted ; then `exit 1`; fi
after_script:
  - coveralls
