version: '3'

services:
  app:
    restart: always
    container_name: mdot 
    build: .
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      - ./mdot:/app/mdot
    ports:
      - "${PORT:-8000}:8000"
    environment:
      ENV: localdev
      RESTCLIENTS_MDOT_DAO_CLASS: ${RESTCLIENTS_MDOT_DAO_CLASS:-Mock}
      RESTCLIENTS_MDOT_HOST: ${RESTCLIENTS_MDOT_HOST:-None}
