version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: mdot_app
    environment:
      GOOGLE_ANALYTICS_KEY: ${GOOGLE_ANALYTICS_KEY}
      ENV: localdev
      AUTH: ${AUTH:-SAML_MOCK}
      RESTCLIENTS_MDOT_DAO_CLASS: ${RESTCLIENTS_MDOT_DAO_CLASS:-Mock}
      RESTCLIENTS_MDOT_HOST: ${RESTCLIENTS_MDOT_HOST:-None}
    volumes:
      - ./mdot:/app/mdot
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  node-bundler:
    build:
      context: .
      target: node-bundler
    restart: always
    container_name: mdot_node
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
      ENV: localdev
    volumes:
      - ./mdot:/app/mdot # expose main django app so webpack-loader can output bundles here
      - ./mdot_vue:/app/mdot_vue
      - statics-volume:/static
    command: npm run watch
    stdin_open: true
    tty: true
volumes:
  statics-volume: