autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

ingress:
  enabled: true
  tls:
    prod-mdot:
      secretName: prod.mdot.uw.edu-ingress-cert
      hosts:
        - prod.mdot.uw.edu
    mobile-uw:
      secretName: mobile.uw.edu-ingress-cert
      hosts:
        - mobile.uw.edu
    m-uw:
      secretName: m.uw.edu-ingress-cert
      hosts:
        - m.uw.edu
    mobile-washington:
      secretName: mobile.washington.edu-ingress-cert
      hosts:
        - mobile.washington.edu
    m-washington:
      secretName: m.washington.edu-ingress-cert
      hosts:
        - m.washington.edu
  hosts:
    prod-mdot:
      host: prod.mdot.uw.edu
      paths:
        - "/"
    mobile-uw:
      host: mobile.uw.edu
      paths:
        - "/"
    m-uw:
      host: m.uw.edu
      paths:
        - "/"
    mobile-washington:
      host: mobile.washington.edu
      paths:
        - "/"
    m-washington:
      host: m.washington.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/configuration-snippet: |
      return 301 https://www.washington.edu/mobile/;

repo: mdot
instance: prod

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 128Mi

service:
  enabled: true
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 9113
      targetPort: 9113
      name: metrics

deploymentInitialization:
  enabled: false

daemon:
  enabled: false

database:
  engine: null

externalService:
  enabled: false

cronjob:
  enabled: false

memcached:
  enabled: false

certs:
  mounted: false

gcsCredentials:
  mounted: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    port: metrics

readiness:
  enabled: false

lifecycle:
  enabled: true

environmentVariables:
  - name: "ENV"
    value: "prod"
